application: pez-db
version: 1
runtime: go
api_version: go1

handlers:
- url: /_ah/remote_api
  script: _go_app
  login: admin

- url: /api/.*
  script: _go_app
  login: admin

- url: /
  static_files: dist/index.html
  upload: index.html
  login: admin

- url: /dist
  static_dir: dist
  login: admin